### ISSUE TITLE
JavaScript Monthly Setup

### ISSUE THREAD

**Issue by mutoe** [thoughtworks-js-community-chengdu/js-catch-up#46]
## Task
- [ ] Get the access for https://github.com/ThoughtWorksInc/JS-Monthly-Chengdu
- [ ] Boot the project (upgrade dependencies)
- [ ] Setup pipeline (github actions)
- [ ] Hello world (publish the Feb monthly) and send email
